

appName: myhelmapp5

port: 80

namespace: default #changed from default for troubleshoot.

configmap:
  name: myhelmapp-configmap-v1
  data:
    CUSTOM_HEADER: 'Back to port 80.'
 
image:
  name: devopsjourney1/mywebapp
  tag: latest

  #Default configuration for you helm chart

  #customize it however you like it will reflect the template.

  #This file contains default values for configurable parameters in your chart. Users can override these values when installing the chart.

  #helm install mywebapp-release webapp1/ --values webapp1/values.yaml

  #helm upgrade mywebapp-release webapp1/ --values webapp1/values.yaml

 