namespace: development

configmap:
  data:
    CUSTOM_HEADER: 'Back to port 80'


#helm install mywebapp-release-dev webapp1/ --values webapp1/values.yaml -f webapp1/values-dev.yaml -n development

#helm upgrade mywebapp-release-dev webapp1/ --values webapp1/values.yaml -f webapp1/values-dev.yaml -n development

# - #Development must match namespace above.