namespace: development

configmap:
  data:
    CUSTOM_HEADER: 'Testing in Dev environment. I will be upgrading via commit and sync argocd. Today date Feb 11th, 2026 #started on DEV environments Date April 4, 2025!'


#helm install mywebapp-release-dev webapp1/ --values webapp1/values.yaml -f webapp1/values-dev.yaml -n development

#helm upgrade mywebapp-release-dev webapp1/ --values webapp1/values.yaml -f webapp1/values-dev.yaml -n development

# - #Development must match namespace above..


#Right command below
#helm upgrade mywebapp-release webapp1/ --values webapp1/values.yaml